# Android World Evaluation Config - Local vLLM
# Usage:
#   python test_android_world.py --config androidworld/eval/configs/Qwen3-VL-4B-Instruct.yaml --num_workers 4
#   ./run_android_world.sh

env:
  console_port: 5556
  grpc_port: 8554
  adb_path: ~/android/platform-tools/adb
  emulator_path: /root/android/emulator/emulator
  avd_name: AndroidWorldAvd
  android_sdk_root: /root/android/
  android_avd_home: /root/android/avd/

llm:
  type: openai
  base_url: http://localhost:8000
  model: UI-Voyager
  temperature: 0.7
  max_tokens: 16384
  top_p: 0.8
  max_retry: 3
  retry_delay: 1.0

agent:
  type: local
  name: Qwen3VL-Agent
  model_name: qwen3vl
  prompt_name: qwen3vl_instruct
  wait_after_action_seconds: 1.5
  use_som: false
  resize: null
  history_len: 30
  sft_data_dir: ./sft_data
  n_history_image: 0

eval:
  suite_family: android_world
  tasks: null # null means all tasks
    # - AudioRecorderRecordAudio
    # - CameraTakePhoto
    # - OpenAppTaskEval
  n_task_combinations: 1
  task_random_seed: null # null means random
  checkpoint_dir: ""
  output_path: ~/android_world/runs
